apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: express-app
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/omar93/express.git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: node:14
        namespace: openshift
      env:
        - name: NPM_RUN
          value: "start"
  output:
    to:
      kind: ImageStreamTag
      name: express-app:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
    - type: "github"
