apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/instance: express
  name: express-app
  namespace: omar
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'express-app:latest'
  runPolicy: Serial
  source:
    git:
      uri: 'https://github.com/omar93/express.git'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'node:14'
      noCache: true
      dockerfilePath: Dockerfile
    type: Docker
  triggers:
    - type: ConfigChange
    - type: ImageChange
    - type: GitHub
      github:
        secretReference:
          name: github-webhook-secret